<a href="https://colab.research.google.com/github/Suhani16-K/numpy/blob/main/Copy_of_Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone https://github.com/Suhani16-K/numpy.git

fatal: destination path 'numpy' already exists and is not an empty directory.


In [ ]:
%cd numpy

/content/numpy


In [ ]:
with open("test.py", "w") as f:
    f.write("print('Hello from Colab')")

In [ ]:
!ls

test.py


In [ ]:
!git add .

In [ ]:
!git config --global user.email "suhanikushwaha16@gmail.com"
!git config --global user.name "Suhani16-K"

In [ ]:
!git commit -m "Added test file"

[main (root-commit) a765187] Added test file
 1 file changed, 1 insertion(+)
 create mode 100644 test.py


In [ ]:
!git push -u origin main

fatal: could not read Username for 'https://github.com': No such device or address


                                            NUMPY

NumPy->fundamental package->scientific computing in Python .
It is a Python library that provides a multidimensional array object.
which include matrices.
justlike there is datatype called as numpy array.
it is used becoz - 1.⚡ Faster.   2. 📊 Supports Arrays (n-dimensional)   3.➕ Easy Mathematical Operations   4.🧠 Used in ML & AI   5.💾 Memory Efficient


In [2]:
import numpy as np

In [3]:
# np.array
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
# 2D and 3D
b=np.array([[1,2,3] , [4,5,6]])
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b,c)
# print(c)

[[1 2 3]
 [4 5 6]] [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
# dtype
np.array([1,2,3],dtype=float)
np.array([2,3,4],dtype=bool)
np.array([1,3,6],dtype=complex)
np.array([1,3,6],dtype=bytes)

array([b'1', b'3', b'6'], dtype='|S1')

In [6]:
# np.arange
np.arange(1,32,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31])

In [7]:
# with reshape
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [8]:
# np.ones and np.zeros
# used for initialising the  weight in DL
np.ones((3,4))
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
# np.random
np.random.random((1,10))

array([[0.12433923, 0.04288077, 0.17280811, 0.2910827 , 0.68390206,
        0.79938587, 0.41598623, 0.79520001, 0.59126421, 0.07246752]])

In [10]:
# np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [11]:
# np.identity
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Array Attributes

In [12]:
# 1d array -> vector
# 2d array -> matrix
# 3d array -> tensor
# (3,2,2)-> (no.of 2D array,rows,cols)
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(16,dtype=float).reshape(4,4)
a3 = np.arange(12).reshape(3,2,2)
print(a3)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [13]:
# ndim
np.ndim(a1)
np.ndim(a2)
np.ndim(a3)

3

In [14]:
# shape
np.shape(a1)
np.shape(a2)
np.shape(a3)

(3, 2, 2)

In [15]:
# size
np.size(a1)
s= np.size(a2)
print(s,a2)
np.size(a3)

16 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


12

In NumPy, memory depends on data type (dtype).

Data Type	Size
int16  	   2 bytes   
int32	     4 bytes   
int64	     8 bytes   
float32    4 bytes   
float64    8 bytes   

In [16]:
# itemsize
print(a1.itemsize) #when int is 32 and when int is 16 then ->2 byte
print(a2.itemsize) #when it is float
print(a3.itemsize) # when int is 64


4
8
8


In [17]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


Changing Datatype

In [18]:
a3.astype(np.int32)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]], dtype=int32)

Array Operations

In [49]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [20]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [21]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [22]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

Array Functions

In [23]:

a1 = np.random.random((3,4))
a1=np.round(a1*100)
print(a1)


[[12. 29. 82. 66.]
 [21. 58. 26. 40.]
 [23. 46.  2. 12.]]


In [24]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.max(a1)
np.min(a1)
np.sum(a1)
np.prod(a1)
np.prod(a1,axis=1)
np.prod(a1,axis=0)

array([ 5796., 77372.,  4264., 31680.])

In [25]:
# mean/median/std/var
np.mean(a1,axis=1)
np.median(a1)
np.std(a1)
np.var(a1,axis=1)

array([783.6875, 206.1875, 267.6875])

In [26]:
# trigonomoetric functions
np.sin(a1)

array([[-0.53657292, -0.66363388,  0.31322878, -0.02655115],
       [ 0.83665564,  0.99287265,  0.76255845,  0.74511316],
       [-0.8462204 ,  0.90178835,  0.90929743, -0.53657292]])

In [27]:
a2=np.random.random((4,2))
# dot product
np.dot(a1,a2)

array([[128.453037  ,  75.6237888 ],
       [107.29736991,  91.0364045 ],
       [ 64.07373948,  65.2459817 ]])

In [28]:
# log and exponents
np.log(a1)
np.exp(a1)

array([[1.62754791e+05, 3.93133430e+12, 4.09399696e+35, 4.60718663e+28],
       [1.31881573e+09, 1.54553894e+25, 1.95729609e+11, 2.35385267e+17],
       [9.74480345e+09, 9.49611942e+19, 7.38905610e+00, 1.62754791e+05]])

In [29]:
# round/floor/ceil
np.round(np.random.random((3,4)))
np.floor(np.random.random((3,4)))
np.ceil(np.random.random((3,4)))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Indexing and Slicing

In [30]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [31]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a1[-1]

np.int64(9)

In [33]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
a2[2,1]

np.int64(9)

In [35]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [36]:
a3[1,1,0]

np.int64(6)

In [37]:
a3[0,0,0]

np.int64(0)

In [38]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a1[3:6:1]

array([3, 4, 5])

In [40]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
a2[0, :]

array([0, 1, 2, 3])

In [42]:
a2[1: ,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [43]:
a2[0:3:2 ,1:5:2]

array([[ 1,  3],
       [ 9, 11]])

In [46]:
a2[1,0: :3]

array([4, 7])

In [48]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [54]:
a3[::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

In [56]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

Iterating

In [61]:
a1
for i in a1:
 print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [64]:
a2
for i in a2:
  print(i)

[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [65]:
a3
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [67]:
#it convert any dimension in 1d array
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Reshaping

In [ ]:
# reshape

In [69]:
# ravel
np.ravel(a3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [70]:
# Transpose
np.transpose(a1)
a1.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

Stacking

In [72]:
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [80]:
# horizontal stacking-> join from left and right
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [81]:
# Vertical stacking-> join from up and down
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Splitting

In [76]:
# horizontal splitting->  split from the middle from vertical

np.hsplit( a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [79]:
# vertical splitting-> split from the middle from horizontal
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]