<a href="https://colab.research.google.com/github/Suhani16-K/numpy/blob/main/Copy_of_Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone https://github.com/Suhani16-K/numpy.git

fatal: destination path 'numpy' already exists and is not an empty directory.


In [ ]:
%cd numpy

/content/numpy


In [ ]:
with open("test.py", "w") as f:
    f.write("print('Hello from Colab')")

In [ ]:
!ls

test.py


In [ ]:
!git add .

In [ ]:
!git config --global user.email "suhanikushwaha16@gmail.com"
!git config --global user.name "Suhani16-K"

In [ ]:
!git commit -m "Added test file"

[main (root-commit) a765187] Added test file
 1 file changed, 1 insertion(+)
 create mode 100644 test.py


In [ ]:
!git push -u origin main

fatal: could not read Username for 'https://github.com': No such device or address


                                            NUMPY

NumPy->fundamental package->scientific computing in Python .
It is a Python library that provides a multidimensional array object.
which include matrices.
justlike there is datatype called as numpy array.
it is used becoz - 1.⚡ Faster.   2. 📊 Supports Arrays (n-dimensional)   3.➕ Easy Mathematical Operations   4.🧠 Used in ML & AI   5.💾 Memory Efficient


In [2]:
import numpy as np

In [2]:
# np.array
a=np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
# 2D and 3D
b=np.array([[1,2,3] , [4,5,6]])
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b,c)
# print(c)

[[1 2 3]
 [4 5 6]] [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
# dtype
np.array([1,2,3],dtype=float)
np.array([2,3,4],dtype=bool)
np.array([1,3,6],dtype=complex)
np.array([1,3,6],dtype=bytes)

array([b'1', b'3', b'6'], dtype='|S1')

In [5]:
# np.arange
np.arange(1,32,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31])

In [6]:
# with reshape
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [7]:
# np.ones and np.zeros
# used for initialising the  weight in DL
np.ones((3,4))
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
# np.random
np.random.random((1,10))

array([[0.94271844, 0.86259292, 0.89350133, 0.23180198, 0.14680443,
        0.00119093, 0.40758771, 0.01012987, 0.59644213, 0.29903593]])

In [9]:
# np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [10]:
# np.identity
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Array Attributes

In [51]:
# 1d array -> vector
# 2d array -> matrix
# 3d array -> tensor
# (3,2,2)-> (no.of 2D array,rows,cols)
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(16,dtype=float).reshape(4,4)
a3 = np.arange(12).reshape(3,2,2)
print(a3)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [28]:
# ndim
np.ndim(a1)
np.ndim(a2)
np.ndim(a3)

3

In [31]:
# shape
np.shape(a1)
np.shape(a2)
np.shape(a3)

(3, 2, 2)

In [53]:
# size
np.size(a1)
s= np.size(a2)
print(s,a2)
np.size(a3)

16 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


12

In NumPy, memory depends on data type (dtype).

Data Type	Size
int16  	   2 bytes   
int32	     4 bytes   
int64	     8 bytes   
float32    4 bytes   
float64    8 bytes   

In [52]:
# itemsize
print(a1.itemsize) #when int is 32 and when int is 16 then ->2 byte
print(a2.itemsize) #when it is float
print(a3.itemsize) # when int is 64


4
8
8


In [48]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int16
float64
int64


Changing Datatype

In [50]:
a3.astype(np.int32)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]], dtype=int32)

Array Operations

In [3]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [4]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [5]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [6]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])