<a href="https://colab.research.google.com/github/Suhani16-K/numpy/blob/main/Copy_of_Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone https://github.com/Suhani16-K/numpy.git

fatal: destination path 'numpy' already exists and is not an empty directory.


In [ ]:
%cd numpy

/content/numpy


In [ ]:
with open("test.py", "w") as f:
    f.write("print('Hello from Colab')")

In [ ]:
!ls

test.py


In [ ]:
!git add .

In [ ]:
!git config --global user.email "suhanikushwaha16@gmail.com"
!git config --global user.name "Suhani16-K"

In [ ]:
!git commit -m "Added test file"

[main (root-commit) a765187] Added test file
 1 file changed, 1 insertion(+)
 create mode 100644 test.py


In [ ]:
!git push -u origin main

fatal: could not read Username for 'https://github.com': No such device or address


                                            NUMPY

NumPy->fundamental package->scientific computing in Python .
It is a Python library that provides a multidimensional array object.
which include matrices.
justlike there is datatype called as numpy array.
it is used becoz - 1.⚡ Faster.   2. 📊 Supports Arrays (n-dimensional)   3.➕ Easy Mathematical Operations   4.🧠 Used in ML & AI   5.💾 Memory Efficient


In [3]:
import numpy as np

In [4]:
# np.array
a=np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
# 2D and 3D
b=np.array([[1,2,3] , [4,5,6]])
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b,c)
# print(c)

[[1 2 3]
 [4 5 6]] [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
# dtype
np.array([1,2,3],dtype=float)
np.array([2,3,4],dtype=bool)
np.array([1,3,6],dtype=complex)
np.array([1,3,6],dtype=bytes)

array([b'1', b'3', b'6'], dtype='|S1')

In [6]:
# np.arange
np.arange(1,32,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31])

In [9]:
# with reshape
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [10]:
# np.ones and np.zeros
# used for initialising the  weight in DL
np.ones((3,4))
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
# np.random
np.random.random((1,10))

array([[0.64448711, 0.83313345, 0.9635568 , 0.34866227, 0.08824044,
        0.95524236, 0.99992598, 0.75111544, 0.38185753, 0.84548061]])

In [12]:
# np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [13]:
# np.identity
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Array Attributes

In [14]:
# 1d array -> vector
# 2d array -> matrix
# 3d array -> tensor
# (3,2,2)-> (no.of 2D array,rows,cols)
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(16,dtype=float).reshape(4,4)
a3 = np.arange(12).reshape(3,2,2)
print(a3)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [15]:
# ndim
np.ndim(a1)
np.ndim(a2)
np.ndim(a3)

3

In [16]:
# shape
np.shape(a1)
np.shape(a2)
np.shape(a3)

(3, 2, 2)

In [17]:
# size
np.size(a1)
s= np.size(a2)
print(s,a2)
np.size(a3)

16 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


12

In NumPy, memory depends on data type (dtype).

Data Type	Size
int16  	   2 bytes   
int32	     4 bytes   
int64	     8 bytes   
float32    4 bytes   
float64    8 bytes   

In [18]:
# itemsize
print(a1.itemsize) #when int is 32 and when int is 16 then ->2 byte
print(a2.itemsize) #when it is float
print(a3.itemsize) # when int is 64


4
8
8


In [19]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


Changing Datatype

In [20]:
a3.astype(np.int32)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]], dtype=int32)

Array Operations

In [21]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [22]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [23]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [24]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

Array Functions

In [33]:

a1 = np.random.random((3,4))
a1=np.round(a1*100)
print(a1)


[[91. 46.  4. 65.]
 [94. 98. 50. 19.]
 [43.  3.  9. 63.]]


In [38]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.max(a1)
np.min(a1)
np.sum(a1)
np.prod(a1)
np.prod(a1,axis=1)
np.prod(a1,axis=0)

array([367822.,  13524.,   1800.,  77805.])

In [42]:
# mean/median/std/var
np.mean(a1,axis=1)
np.median(a1)
np.std(a1)
np.var(a1,axis=1)

array([1007.25  , 1067.6875,  606.75  ])

In [48]:
# trigonomoetric functions
np.sin(a1)

array([[ 0.10598751,  0.90178835, -0.7568025 ,  0.82682868],
       [-0.24525199, -0.57338187, -0.26237485,  0.14987721],
       [-0.83177474,  0.14112001,  0.41211849,  0.1673557 ]])

In [55]:
a2=np.random.random((4,2))
# dot product
np.dot(a1,a2)

array([[105.97172383, 123.28370931],
       [133.23821669, 132.47037899],
       [ 66.83091749,  90.83066342]])

In [57]:
# log and exponents
np.log(a1)
np.exp(a1)

array([[3.31740010e+39, 9.49611942e+19, 5.45981500e+01, 1.69488924e+28],
       [6.66317622e+40, 3.63797095e+42, 5.18470553e+21, 1.78482301e+08],
       [4.72783947e+18, 2.00855369e+01, 8.10308393e+03, 2.29378316e+27]])

In [59]:
# round/floor/ceil
np.round(np.random.random((3,4)))
np.floor(np.random.random((3,4)))
np.ceil(np.random.random((3,4)))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Indexing and Slicing

In [63]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [64]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
a1[-1]

np.int64(9)

In [68]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
a2[2,1]

np.int64(9)

In [71]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [72]:
a3[1,1,0]

np.int64(6)

In [73]:
a3[0,0,0]

np.int64(0)

In [74]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
a1[3:6:1]

array([3, 4, 5])

In [80]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [81]:
a2[0, :]

array([0, 1, 2, 3])

In [83]:
a2[1: ,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [84]:
a2[0:3:2 ,1:5:2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[]