<a href="https://colab.research.google.com/github/Suhani16-K/numpy/blob/main/Copy_of_Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone https://github.com/Suhani16-K/numpy.git

fatal: destination path 'numpy' already exists and is not an empty directory.


In [ ]:
%cd numpy

/content/numpy


In [ ]:
with open("test.py", "w") as f:
    f.write("print('Hello from Colab')")

In [ ]:
!ls

test.py


In [ ]:
!git add .

In [ ]:
!git config --global user.email "suhanikushwaha16@gmail.com"
!git config --global user.name "Suhani16-K"

In [ ]:
!git commit -m "Added test file"

[main (root-commit) a765187] Added test file
 1 file changed, 1 insertion(+)
 create mode 100644 test.py


In [ ]:
!git push -u origin main

fatal: could not read Username for 'https://github.com': No such device or address


                                            NUMPY

NumPy->fundamental package->scientific computing in Python .
It is a Python library that provides a multidimensional array object.
which include matrices.
justlike there is datatype called as numpy array.
it is used becoz - 1.⚡ Faster.   2. 📊 Supports Arrays (n-dimensional)   3.➕ Easy Mathematical Operations   4.🧠 Used in ML & AI   5.💾 Memory Efficient


In [1]:
import numpy as np

In [2]:
# np.array
a=np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
# 2D and 3D
b=np.array([[1,2,3] , [4,5,6]])
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b,c)
# print(c)

[[1 2 3]
 [4 5 6]] [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
# dtype
np.array([1,2,3],dtype=float)
np.array([2,3,4],dtype=bool)
np.array([1,3,6],dtype=complex)
np.array([1,3,6],dtype=bytes)

array([b'1', b'3', b'6'], dtype='|S1')

In [5]:
# np.arange
np.arange(1,32,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31])

In [6]:
# with reshape
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [7]:
# np.ones and np.zeros
# used for initialising the  weight in DL
np.ones((3,4))
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
# np.random
np.random.random((1,10))

array([[0.66605257, 0.90063227, 0.10761126, 0.73077003, 0.80010639,
        0.62566894, 0.71706639, 0.57607772, 0.8794352 , 0.44649881]])

In [9]:
# np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [10]:
# np.identity
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Array Attributes

In [11]:
# 1d array -> vector
# 2d array -> matrix
# 3d array -> tensor
# (3,2,2)-> (no.of 2D array,rows,cols)
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(16,dtype=float).reshape(4,4)
a3 = np.arange(12).reshape(3,2,2)
print(a3)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [12]:
# ndim
np.ndim(a1)
np.ndim(a2)
np.ndim(a3)

3

In [13]:
# shape
np.shape(a1)
np.shape(a2)
np.shape(a3)

(3, 2, 2)

In [14]:
# size
np.size(a1)
s= np.size(a2)
print(s,a2)
np.size(a3)

16 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


12

In NumPy, memory depends on data type (dtype).

Data Type	Size
int16  	   2 bytes   
int32	     4 bytes   
int64	     8 bytes   
float32    4 bytes   
float64    8 bytes   

In [15]:
# itemsize
print(a1.itemsize) #when int is 32 and when int is 16 then ->2 byte
print(a2.itemsize) #when it is float
print(a3.itemsize) # when int is 64


4
8
8


In [16]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


Changing Datatype

In [17]:
a3.astype(np.int32)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]], dtype=int32)

Array Operations

In [18]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [19]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [20]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [21]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

Array Functions

In [22]:

a1 = np.random.random((3,4))
a1=np.round(a1*100)
print(a1)


[[20. 57. 86. 65.]
 [88. 69. 33. 68.]
 [48. 86. 84. 15.]]


In [23]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.max(a1)
np.min(a1)
np.sum(a1)
np.prod(a1)
np.prod(a1,axis=1)
np.prod(a1,axis=0)

array([ 84480., 338238., 238392.,  66300.])

In [24]:
# mean/median/std/var
np.mean(a1,axis=1)
np.median(a1)
np.std(a1)
np.var(a1,axis=1)

array([568.5   , 394.25  , 852.1875])

In [25]:
# trigonomoetric functions
np.sin(a1)

array([[ 0.91294525,  0.43616476, -0.92345845,  0.82682868],
       [ 0.0353983 , -0.11478481,  0.99991186, -0.89792768],
       [-0.76825466, -0.92345845,  0.73319032,  0.65028784]])

In [26]:
a2=np.random.random((4,2))
# dot product
np.dot(a1,a2)

array([[ 61.63695154,  94.65036068],
       [ 98.69557487, 135.91892578],
       [ 66.70618104, 113.42207711]])

In [27]:
# log and exponents
np.log(a1)
np.exp(a1)

array([[4.85165195e+08, 5.68572000e+24, 2.23524660e+37, 1.69488924e+28],
       [1.65163625e+38, 9.25378173e+29, 2.14643580e+14, 3.40427605e+29],
       [7.01673591e+20, 2.23524660e+37, 3.02507732e+36, 3.26901737e+06]])

In [28]:
# round/floor/ceil
np.round(np.random.random((3,4)))
np.floor(np.random.random((3,4)))
np.ceil(np.random.random((3,4)))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Indexing and Slicing

In [29]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [30]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a1[-1]

np.int64(9)

In [32]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
a2[2,1]

np.int64(9)

In [34]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [35]:
a3[1,1,0]

np.int64(6)

In [36]:
a3[0,0,0]

np.int64(0)

In [37]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a1[3:6:1]

array([3, 4, 5])

In [39]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
a2[0, :]

array([0, 1, 2, 3])

In [41]:
a2[1: ,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [42]:
a2[0:3:2 ,1:5:2]

array([[ 1,  3],
       [ 9, 11]])

In [43]:
a2[1,0: :3]

array([4, 7])

In [44]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [45]:
a3[::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

In [46]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

Iterating

In [47]:
a1
for i in a1:
 print(i)

0
1
2
3
4
5
6
7
8
9


In [48]:
a2
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [49]:
a3
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [50]:
#it convert any dimension in 1d array
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Reshaping

In [51]:
# reshape

In [52]:
# ravel
np.ravel(a3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [53]:
# Transpose
np.transpose(a1)
a1.T

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Stacking

In [54]:
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [55]:
# horizontal stacking-> join from left and right
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [56]:
# Vertical stacking-> join from up and down
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Splitting

In [57]:
# horizontal splitting->  split from the middle from vertical

np.hsplit( a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [58]:
# vertical splitting-> split from the middle from horizontal
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

Numpy array vs Python lists

In [59]:
# speed -> numpy array speed is approx 50 times fast than list
# list
a= [i for i in range(10000000)]
b= [i for i in range(10000000,20000000)]
c=[]
import time
start=time.time()
for i in range(len(a)):
  c.append(a[i]+b[i])
print(time.time()-start)


1.7902610301971436


In [61]:
# numpy
a=np.array([10000000])
b=np.array([10000000,20000000])
start=time.time()
c=a+b
print(time.time()-start)

0.16860318183898926


In [63]:
# memory
a =[i for i in range(10000000)]
import sys
sys.getsizeof(a)

89095160

In [65]:
a=np.array([10000000])
sys.getsizeof(a)

120

In [ ]:
# convenience