<a href="https://colab.research.google.com/github/Suhani16-K/numpy/blob/main/Copy_of_Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone https://github.com/Suhani16-K/numpy.git

fatal: destination path 'numpy' already exists and is not an empty directory.


In [ ]:
%cd numpy

/content/numpy


In [ ]:
with open("test.py", "w") as f:
    f.write("print('Hello from Colab')")

In [ ]:
!ls

test.py


In [ ]:
!git add .

In [ ]:
!git config --global user.email "suhanikushwaha16@gmail.com"
!git config --global user.name "Suhani16-K"

In [ ]:
!git commit -m "Added test file"

[main (root-commit) a765187] Added test file
 1 file changed, 1 insertion(+)
 create mode 100644 test.py


In [ ]:
!git push -u origin main

fatal: could not read Username for 'https://github.com': No such device or address


                                            NUMPY

NumPy->fundamental package->scientific computing in Python .
It is a Python library that provides a multidimensional array object.
which include matrices.
justlike there is datatype called as numpy array.
it is used becoz - 1.⚡ Faster.   2. 📊 Supports Arrays (n-dimensional)   3.➕ Easy Mathematical Operations   4.🧠 Used in ML & AI   5.💾 Memory Efficient


In [3]:
import numpy as np

In [4]:
# np.array
a=np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
# 2D and 3D
b=np.array([[1,2,3] , [4,5,6]])
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b,c)
# print(c)

[[1 2 3]
 [4 5 6]] [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
# dtype
np.array([1,2,3],dtype=float)
np.array([2,3,4],dtype=bool)
np.array([1,3,6],dtype=complex)
np.array([1,3,6],dtype=bytes)

array([b'1', b'3', b'6'], dtype='|S1')

In [7]:
# np.arange
np.arange(1,32,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31])

In [8]:
# with reshape
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [9]:
# np.ones and np.zeros
# used for initialising the  weight in DL
np.ones((3,4))
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
# np.random
np.random.random((1,10))

array([[0.11595638, 0.09850417, 0.9469927 , 0.00606577, 0.61854703,
        0.21554689, 0.48621622, 0.27124032, 0.36770016, 0.39513996]])

In [11]:
# np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [12]:
# np.identity
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Array Attributes

In [13]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])