<a href="https://colab.research.google.com/github/Suhani16-K/numpy/blob/main/Copy_of_Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
!git clone https://github.com/Suhani16-K/numpy.git

fatal: destination path 'numpy' already exists and is not an empty directory.


In [13]:
%cd numpy

/content/numpy


In [19]:
with open("test.py", "w") as f:
    f.write("print('Hello from Colab')")

In [20]:
!ls

test.py


In [23]:
!git add .

In [25]:
!git config --global user.email "suhanikushwaha16@gmail.com"
!git config --global user.name "Suhani16-K"

In [26]:
!git commit -m "Added test file"

[main (root-commit) a765187] Added test file
 1 file changed, 1 insertion(+)
 create mode 100644 test.py


In [28]:
!git push -u origin main

fatal: could not read Username for 'https://github.com': No such device or address


                                            NUMPY

NumPy->fundamental package->scientific computing in Python .
It is a Python library that provides a multidimensional array object.
which include matrices.
justlike there is datatype called as numpy array.
it is used becoz - 1.⚡ Faster.   2. 📊 Supports Arrays (n-dimensional)   3.➕ Easy Mathematical Operations   4.🧠 Used in ML & AI   5.💾 Memory Efficient


In [2]:
import numpy as np

In [3]:
# np.array
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
# 2D and 3D
b=np.array([[1,2,3] , [4,5,6]])
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b,c)
# print(c)

[[1 2 3]
 [4 5 6]] [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
# dtype
np.array([1,2,3],dtype=float)
np.array([2,3,4],dtype=bool)
np.array([1,3,6],dtype=complex)
np.array([1,3,6],dtype=bytes)

array([b'1', b'3', b'6'], dtype='|S1')

In [6]:
# np.arange
np.arange(1,32,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31])

In [7]:
# with reshape
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [8]:
# np.ones and np.zeros
# used for initialising the  weight in DL
np.ones((3,4))
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
# np.random
np.random.random((1,10))

array([[0.33220447, 0.26968666, 0.7133939 , 0.54323124, 0.59501397,
        0.05309721, 0.00332549, 0.9829089 , 0.2108637 , 0.14796399]])

In [10]:
# np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [11]:
# np.identity
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])