<a href="https://colab.research.google.com/github/Suhani16-K/numpy/blob/main/Copy_of_Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone https://github.com/Suhani16-K/numpy.git

fatal: destination path 'numpy' already exists and is not an empty directory.


In [ ]:
%cd numpy

/content/numpy


In [ ]:
with open("test.py", "w") as f:
    f.write("print('Hello from Colab')")

In [ ]:
!ls

test.py


In [ ]:
!git add .

In [ ]:
!git config --global user.email "suhanikushwaha16@gmail.com"
!git config --global user.name "Suhani16-K"

In [ ]:
!git commit -m "Added test file"

[main (root-commit) a765187] Added test file
 1 file changed, 1 insertion(+)
 create mode 100644 test.py


In [ ]:
!git push -u origin main

fatal: could not read Username for 'https://github.com': No such device or address


                                            NUMPY

NumPy->fundamental package->scientific computing in Python .
It is a Python library that provides a multidimensional array object.
which include matrices.
justlike there is datatype called as numpy array.
it is used becoz - 1.⚡ Faster.   2. 📊 Supports Arrays (n-dimensional)   3.➕ Easy Mathematical Operations   4.🧠 Used in ML & AI   5.💾 Memory Efficient


In [ ]:
import numpy as np

In [ ]:
# np.array
a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
# 2D and 3D
b=np.array([[1,2,3] , [4,5,6]])
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b,c)
# print(c)

[[1 2 3]
 [4 5 6]] [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# dtype
np.array([1,2,3],dtype=float)
np.array([2,3,4],dtype=bool)
np.array([1,3,6],dtype=complex)
np.array([1,3,6],dtype=bytes)

array([b'1', b'3', b'6'], dtype='|S1')

In [ ]:
# np.arange
np.arange(1,32,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31])

In [ ]:
# with reshape
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
# np.ones and np.zeros
# used for initialising the  weight in DL
np.ones((3,4))
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np.random
np.random.random((1,10))

array([[0.08556921, 0.36651471, 0.68811572, 0.67309484, 0.92316311,
        0.31525134, 0.06005189, 0.44180382, 0.85271506, 0.78271943]])

In [ ]:
# np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
# np.identity
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Array Attributes

In [ ]:
# 1d array -> vector
# 2d array -> matrix
# 3d array -> tensor
# (3,2,2)-> (no.of 2D array,rows,cols)
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(16,dtype=float).reshape(4,4)
a3 = np.arange(12).reshape(3,2,2)
print(a3)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [ ]:
# ndim
np.ndim(a1)
np.ndim(a2)
np.ndim(a3)

3

In [ ]:
# shape
np.shape(a1)
np.shape(a2)
np.shape(a3)

(3, 2, 2)

In [ ]:
# size
np.size(a1)
s= np.size(a2)
print(s,a2)
np.size(a3)

16 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


12

In NumPy, memory depends on data type (dtype).

Data Type	Size
int16  	   2 bytes   
int32	     4 bytes   
int64	     8 bytes   
float32    4 bytes   
float64    8 bytes   

In [ ]:
# itemsize
print(a1.itemsize) #when int is 32 and when int is 16 then ->2 byte
print(a2.itemsize) #when it is float
print(a3.itemsize) # when int is 64


4
8
8


In [ ]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


Changing Datatype

In [ ]:
a3.astype(np.int32)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]], dtype=int32)

Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

Array Functions

In [ ]:

a1 = np.random.random((3,4))
a1=np.round(a1*100)
print(a1)


[[ 30.   2.  83.  95.]
 [100.  26.  67.  16.]
 [ 40.  55.  36.  54.]]


In [ ]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.max(a1)
np.min(a1)
np.sum(a1)
np.prod(a1)
np.prod(a1,axis=1)
np.prod(a1,axis=0)

array([120000.,   2860., 200196.,  82080.])

In [ ]:
# mean/median/std/var
np.mean(a1,axis=1)
np.median(a1)
np.std(a1)
np.var(a1,axis=1)

array([1448.25  , 1125.1875,   70.1875])

In [ ]:
# trigonomoetric functions
np.sin(a1)

array([[-0.98803162,  0.90929743,  0.96836446,  0.68326171],
       [-0.50636564,  0.76255845, -0.85551998, -0.28790332],
       [ 0.74511316, -0.99975517, -0.99177885, -0.55878905]])

In [ ]:
a2=np.random.random((4,2))
# dot product
np.dot(a1,a2)

array([[36.3494126 , 94.92102541],
       [70.23157636, 98.380832  ],
       [60.94462712, 73.54259096]])

In [ ]:
# log and exponents
np.log(a1)
np.exp(a1)

array([[1.06864746e+13, 7.38905610e+00, 1.11286375e+36, 1.81123908e+41],
       [2.68811714e+43, 1.95729609e+11, 1.25236317e+29, 8.88611052e+06],
       [2.35385267e+17, 7.69478527e+23, 4.31123155e+15, 2.83075330e+23]])

In [ ]:
# round/floor/ceil
np.round(np.random.random((3,4)))
np.floor(np.random.random((3,4)))
np.ceil(np.random.random((3,4)))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Indexing and Slicing

In [ ]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[-1]

np.int64(9)

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[2,1]

np.int64(9)

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,1,0]

np.int64(6)

In [ ]:
a3[0,0,0]

np.int64(0)

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[3:6:1]

array([3, 4, 5])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0, :]

array([0, 1, 2, 3])

In [ ]:
a2[1: ,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a2[0:3:2 ,1:5:2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1,0: :3]

array([4, 7])

In [ ]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

Iterating

In [ ]:
a1
for i in a1:
 print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a3
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
#it convert any dimension in 1d array
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Reshaping

In [ ]:
# reshape

In [ ]:
# ravel
np.ravel(a3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [ ]:
# Transpose
np.transpose(a1)
a1.T

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Stacking

In [ ]:
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# horizontal stacking-> join from left and right
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# Vertical stacking-> join from up and down
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Splitting

In [ ]:
# horizontal splitting->  split from the middle from vertical

np.hsplit( a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
# vertical splitting-> split from the middle from horizontal
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

Numpy array vs Python lists

In [ ]:
# speed -> numpy array speed is approx 50 times fast than list
# list
a= [i for i in range(10000000)]
b= [i for i in range(10000000,20000000)]
c=[]
import time
start=time.time()
for i in range(len(a)):
  c.append(a[i]+b[i])
print(time.time()-start)


3.2413883209228516


In [ ]:
# numpy
a=np.array([10000000])
b=np.array([10000000,20000000])
start=time.time()
c=a+b
print(time.time()-start)

0.16193699836730957


In [ ]:
# memory
a =[i for i in range(10000000)]
import sys
sys.getsizeof(a)

89095160

In [ ]:
a=np.array([10000000])
sys.getsizeof(a)

120

In [ ]:
# convenience

Advanced Indexing

In [ ]:
# Normal Indexing and slicing
a=np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a[2: ,1:]

array([[ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19],
       [21, 22, 23]])

In [ ]:
# Fancy Indexing  -> Fancy Indexing is a powerful feature in NumPy that allows you to select multiple elements from an array using lists/arrays
# of indices instead of simple slicing.
a[[2,0,1]]  #it showing rows index

array([[ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [ ]:
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [ ]:
# Boolean Indexing
#It means selecting elements from an array using True/False conditions.
#True → select element
#False → ignore element
a=np.random.randint(1,100,24).reshape(6,4)
a

array([[78, 32, 42, 41],
       [75, 91, 52, 17],
       [15, 22, 45, 93],
       [43, 25, 57, 51],
       [ 5, 87, 23, 11],
       [13, 80, 48, 70]])

In [ ]:
# find all numbers greater than 50
a[a>50]

array([78, 75, 91, 52, 93, 57, 51, 87, 80, 70])

In [ ]:
# find out even numbers
a[a%2==0]

array([78, 32, 42, 52, 22, 80, 48, 70])

In [ ]:
# find all numbers greater than 50 and are even
a[(a>50) & (a%2==0)]

array([78, 52, 80, 70])

In [ ]:
# find all numbers not divisible by 7
a[~(a%7==0)]

array([78, 32, 41, 75, 52, 17, 15, 22, 45, 93, 43, 25, 57, 51,  5, 87, 23,
       11, 13, 80, 48])

Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

The smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [ ]:
# same shape
a= np.arange(6).reshape(2,3)
b= np.arange(6,12).reshape(2,3)
print(a ,"\n",b)
a+b

[[0 1 2]
 [3 4 5]] 
 [[ 6  7  8]
 [ 9 10 11]]


array([[ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
# diff shape
c=np.arange(3).reshape(1,3)
d=np.arange(6,12).reshape(2,3)
print(c,"\n",d)
c+d

[[0 1 2]] 
 [[ 6  7  8]
 [ 9 10 11]]


array([[ 6,  8, 10],
       [ 9, 11, 13]])

**Broadcasting** **Rules**
# *italicized text*
1. *Make the two arrays have the same number of dimensions.*

*  If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.



2.* Make each dimension of the two arrays the same size.*

*   If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
*  If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.



<img src = "https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png">

In [ ]:
a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)

print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [ ]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)

print(a)
print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [ ]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print(b)

print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print(b)

print(a + b)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [ ]:
a = np.array([1])
# shape -> (1,1)
b = np.arange(4).reshape(2,2)
# shape -> (2,2)

print(a)
print(b)

print(a+b)

[1]
[[0 1]
 [2 3]]
[[1 2]
 [3 4]]


In [ ]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [ ]:
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)

print(a)
print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]


ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

**Working** **with** **mathematical** **formula**